-- 일정산 VS 집계 건수 비교검증
SELECT 
     DATA.TSDATE
    ,DATA.CUSTCODE
    ,DATA.CNTRCODE
    ,MAS.CNTRNAME
    ,DATA.SRVTYPE
    ,DATA."SCI.APRCNT"
    ,DATA."TOT.APRCNT"
    ,DATA."DIFF_APRCNT"
    ,DATA."SCI.REJCNT"
    ,DATA."TOT.REJCNT"
    ,DATA."DIFF_REJCNT"
    ,DATA."SCI.CANCNT"
    ,DATA."TOT.CANCNT"
    ,DATA."DIFF_CANCNT"
    ,DATA."SCI.REJ_CANCNT"
    ,DATA."TOT.REJCANCNT"
    ,DATA."DIFF_REJCANCNT"
FROM
(
    SELECT
        TOT.CUSTCODE, TOT.CNTRCODE, TOT.TSDATE, TOT.SRVTYPE, 
        SCI.APRCNT "SCI.APRCNT", TOT.APRCNT "TOT.APRCNT", 
        CASE WHEN SCI.APRCNT-TOT.APRCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.APRCNT-TOT.APRCNT) ||')' end "DIFF_APRCNT",
        SCI.REJCNT "SCI.REJCNT", TOT.REJCNT "TOT.REJCNT", 
        CASE WHEN SCI.REJCNT-TOT.REJCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.REJCNT-TOT.REJCNT) ||')' end "DIFF_REJCNT",
        SCI.CANCNT "SCI.CANCNT", TOT.CANCNT "TOT.CANCNT", 
        CASE WHEN ABS(SCI.CANCNT)-ABS(TOT.CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.CANCNT)-ABS(TOT.CANCNT)) ||')' end "DIFF_CANCNT",
        SCI.REJ_CANCNT "SCI.REJ_CANCNT", TOT.REJ_CANCNT "TOT.REJCANCNT", 
        CASE WHEN ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT)) ||')' end "DIFF_REJCANCNT"
    FROM
    (
        SELECT 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE, 
            SUM(CASE WHEN RETTYPE = 'APR' THEN 1 ELSE 0 END) "APRCNT",
            SUM(CASE WHEN RETTYPE = 'CAN' THEN 1 ELSE 0 END) "CANCNT",
            SUM(CASE WHEN RETTYPE = 'REJ' THEN 1 ELSE 0 END) "REJCNT",
            SUM(CASE WHEN RETTYPE = 'REJ_CAN' THEN 1 ELSE 0 END) "REJ_CANCNT"
        FROM 
            SCI_TLFRMOTO
        WHERE 1=1
            AND CUSTCODE = '0100'
            AND TSDATE   = :gTO_DAT
            AND ( BILLEX IS NULL OR BILLEX = '**' )
        GROUP BY 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
        ORDER BY 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
    ) SCI, 
    (
        SELECT 
            CUSTCODE, CNTRCODE, TSDATE, SRVTYPE, APRCNT, REJCNT, CANCNT, REJCANCNT REJ_CANCNT
        FROM SCI_TLF_TOTAL
        WHERE 1=1
            AND CUSTCODE = '0100'
            AND CALSTEP  = '1' 
            AND CALMON   = :gCALMON
    ) TOT
    WHERE 1=1
        AND SCI.CUSTCODE = TOT.CUSTCODE
        AND SCI.CNTRCODE = TOT.CNTRCODE
        AND SCI.CALDATE = TOT.TSDATE
        AND SCI.SRVTYPE = TOT.SRVTYPE
    
        UNION ALL
        
    SELECT
        TOT.CUSTCODE, TOT.CNTRCODE, TOT.TSDATE, TOT.SRVTYPE, 
        SCI.APRCNT "SCI.APRCNT", TOT.APRCNT "TOT.APRCNT", 
        CASE WHEN SCI.APRCNT-TOT.APRCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.APRCNT-TOT.APRCNT) ||')' end "DIFF_APRCNT",
        SCI.REJCNT "SCI.REJCNT", TOT.REJCNT "TOT.REJCNT", 
        CASE WHEN SCI.REJCNT-TOT.REJCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.REJCNT-TOT.REJCNT) ||')' end "DIFF_REJCNT",
        SCI.CANCNT "SCI.CANCNT", TOT.CANCNT "TOT.CANCNT", 
        CASE WHEN ABS(SCI.CANCNT)-ABS(TOT.CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.CANCNT)-ABS(TOT.CANCNT)) ||')' end "DIFF_CANCNT",
        SCI.REJ_CANCNT "SCI.REJ_CANCNT", TOT.REJ_CANCNT "TOT.REJCANCNT", 
        CASE WHEN ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT)) ||')' end "DIFF_REJCANCNT"
    FROM
    (
        SELECT 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE, 
            SUM(CASE WHEN RETTYPE = 'APR' THEN 1 ELSE 0 END) "APRCNT",
            SUM(CASE WHEN RETTYPE = 'CAN' THEN 1 ELSE 0 END) "CANCNT",
            SUM(CASE WHEN RETTYPE = 'REJ' THEN 1 ELSE 0 END) "REJCNT",
            SUM(CASE WHEN RETTYPE = 'REJ_CAN' THEN 1 ELSE 0 END) "REJ_CANCNT"
        FROM SCI_TLF_BUYS_ACQ
        WHERE 1=1
            AND CUSTCODE = '0100'
            AND BILLDT = :gTO_DAT
            AND ( BILLEX IS NULL OR BILLEX = '**' )
            GROUP BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
            ORDER BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
    ) SCI, 
    (
        SELECT 
            CUSTCODE, CNTRCODE, TSDATE, SRVTYPE, APRCNT, REJCNT, CANCNT, REJCANCNT REJ_CANCNT
         FROM SCI_TLF_TOTAL
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND CALSTEP  = '1' 
        AND CALMON   = :gCALMON
    ) TOT
    WHERE 1=1
    AND SCI.CUSTCODE = TOT.CUSTCODE
    AND SCI.CNTRCODE = TOT.CNTRCODE
    AND SCI.CALDATE   = TOT.TSDATE
    AND SCI.SRVTYPE  = TOT.SRVTYPE
    
        UNION ALL
        
    SELECT
        TOT.CUSTCODE, TOT.CNTRCODE, TOT.TSDATE, TOT.SRVTYPE, 
        SCI.APRCNT "SCI.APRCNT", TOT.APRCNT "TOT.APRCNT", 
        CASE WHEN SCI.APRCNT-TOT.APRCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.APRCNT-TOT.APRCNT) ||')' end "DIFF_APRCNT",
        SCI.REJCNT "SCI.REJCNT", TOT.REJCNT "TOT.REJCNT", 
        CASE WHEN SCI.REJCNT-TOT.REJCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.REJCNT-TOT.REJCNT) ||')' end "DIFF_REJCNT",
        SCI.CANCNT "SCI.CANCNT", TOT.CANCNT "TOT.CANCNT", 
        CASE WHEN ABS(SCI.CANCNT)-ABS(TOT.CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.CANCNT)-ABS(TOT.CANCNT)) ||')' end "DIFF_CANCNT",
        SCI.REJ_CANCNT "SCI.REJ_CANCNT", TOT.REJ_CANCNT "TOT.REJCANCNT", 
        CASE WHEN ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT)) ||')' end "DIFF_REJCANCNT"
    FROM
    (
        SELECT 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE, 
            SUM(CASE WHEN RETTYPE = 'APR' THEN 1 ELSE 0 END) "APRCNT",
            SUM(CASE WHEN RETTYPE = 'CAN' THEN 1 ELSE 0 END) "CANCNT",
            SUM(CASE WHEN RETTYPE = 'REJ' THEN 1 ELSE 0 END) "REJCNT",
            SUM(CASE WHEN RETTYPE = 'REJ_CAN' THEN 1 ELSE 0 END) "REJ_CANCNT"
        FROM SCI_EDI_BUYS_ACQ
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND BILLDT = :gTO_DAT
        AND ( BILLEX IS NULL OR BILLEX = '**' )
        GROUP BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
        ORDER BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
    ) SCI, 
    (
        SELECT 
            CUSTCODE, CNTRCODE, TSDATE, SRVTYPE, APRCNT, REJCNT, CANCNT, REJCANCNT REJ_CANCNT
         FROM SCI_TLF_TOTAL
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND CALSTEP  = '1' 
        AND CALMON   = :gCALMON
    ) TOT
    WHERE 1=1
    AND SCI.CUSTCODE = TOT.CUSTCODE
    AND SCI.CNTRCODE = TOT.CNTRCODE
    AND SCI.CALDATE = TOT.TSDATE
    AND SCI.SRVTYPE = TOT.SRVTYPE
    
        UNION ALL
        
    SELECT
        TOT.CUSTCODE, TOT.CNTRCODE, TOT.TSDATE, TOT.SRVTYPE, 
        SCI.APRCNT "SCI.APRCNT", TOT.APRCNT "TOT.APRCNT", 
        CASE WHEN SCI.APRCNT-TOT.APRCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.APRCNT-TOT.APRCNT) ||')' end "DIFF_APRCNT",
        SCI.REJCNT "SCI.REJCNT", TOT.REJCNT "TOT.REJCNT", 
        CASE WHEN SCI.REJCNT-TOT.REJCNT = 0 then '건수일치' else '건수불일치('|| to_number(SCI.REJCNT-TOT.REJCNT) ||')' end "DIFF_REJCNT",
        SCI.CANCNT "SCI.CANCNT", TOT.CANCNT "TOT.CANCNT", 
        CASE WHEN ABS(SCI.CANCNT)-ABS(TOT.CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.CANCNT)-ABS(TOT.CANCNT)) ||')' end "DIFF_CANCNT",
        SCI.REJ_CANCNT "SCI.REJ_CANCNT", TOT.REJ_CANCNT "TOT.REJCANCNT", 
        CASE WHEN ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT) = 0 then '건수일치' else '건수불일치('|| to_number(ABS(SCI.REJ_CANCNT)-ABS(TOT.REJ_CANCNT)) ||')' end "DIFF_REJCANCNT"
    FROM
    (
        SELECT 
            CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE, 
            SUM(CASE WHEN RETTYPE = 'APR' THEN 1 ELSE 0 END) "APRCNT",
            SUM(CASE WHEN RETTYPE = 'CAN' THEN 1 ELSE 0 END) "CANCNT",
            SUM(CASE WHEN RETTYPE = 'REJ' THEN 1 ELSE 0 END) "REJCNT",
            SUM(CASE WHEN RETTYPE = 'REJ_CAN' THEN 1 ELSE 0 END) "REJ_CANCNT"
        FROM SCI_TLF_BUYS_FEE
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND BILLDT = :gTO_DAT
        AND ( BILLEX IS NULL OR BILLEX = '**' )
        GROUP BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
        ORDER BY CUSTCODE, CNTRCODE, BILLDT, CALDATE, SRVTYPE
    ) SCI, 
    (
        SELECT 
            CUSTCODE, CNTRCODE, TSDATE, SRVTYPE, APRCNT, REJCNT, CANCNT, REJCANCNT REJ_CANCNT
         FROM SCI_TLF_TOTAL
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND CALSTEP  = '1' 
        AND CALMON   = :gCALMON
    ) TOT
    WHERE 1=1
    AND SCI.CUSTCODE = TOT.CUSTCODE
    AND SCI.CNTRCODE = TOT.CNTRCODE
    AND SCI.CALDATE = TOT.TSDATE
    AND SCI.SRVTYPE = TOT.SRVTYPE
) DATA, SCI_CNTR_MAS MAS
WHERE 1=1
    AND DATA.CUSTCODE = MAS.CUSTCODE
    AND DATA.CNTRCODE = MAS.CNTRCODE
ORDER BY DATA.CUSTCODE, DATA.CNTRCODE, DATA.TSDATE, DATA.SRVTYPE
;



-- 기관별 집계 VS 명세 건수/금액 비교검증
SELECT 
     TOT.CUSTCODE
    ,TOT.CNTRCODE
    ,TOT.CNTRNAME
    ,TOT.CNT "TOT.CNT"
    ,PRC.SECTCNT "PRC.SECTCNT"
    ,CASE WHEN TOT.CNT - PRC.SECTCNT = 0 then '건수일치' 
          else '건수불일치('|| to_number(TOT.CNT - PRC.SECTCNT) ||')' end "DIFF_CNT"
    ,TOT.AMT_TR "TOT.AMT_TR"
    ,PRC.SECTAMT_TR "PRC.SECTAMT_TR"
    ,CASE WHEN TOT.AMT_TR - PRC.SECTAMT_TR = 0 then '거래금액일치' 
          else '거래금액불일치('|| to_number(TOT.AMT_TR - PRC.SECTAMT_TR) ||')' end "DIFF_AMT"
FROM
    (
        -- 명세
        SELECT 
            CUSTCODE, CNTRCODE, SUM(SECTCNT) SECTCNT, SUM(SECTAMT_TR) SECTAMT_TR
        FROM SCI_TR_SPEC_PRC
        WHERE 1=1
        AND CUSTCODE = '0100'
        AND CALMON = :gCALMON
        AND CALSTEP = '1'
        AND SECTCNT+SECTAMT+SECTAMT_TR+SUPPRC+TAXAMT+TOTAMT+TOTFEEAMT <> 0
        GROUP BY CUSTCODE, CNTRCODE
        ORDER BY CUSTCODE, CNTRCODE
    ) PRC,
    (
        -- 집계
        SELECT 
            TOT.CUSTCODE, TOT.CNTRCODE, MAS.CNTRNAME,
            SUM(APRCNT)-ABS(SUM(CANCNT))+SUM(REJCNT)-ABS(SUM(REJCANCNT)) CNT,
            SUM(APRAMT)-ABS(SUM(CANAMT))+SUM(REJAMT)-ABS(SUM(REJCANAMT)) AMT_TR
         FROM SCI_TLF_TOTAL TOT, SCI_CNTR_MAS MAS
        WHERE 1=1
        AND TOT.CUSTCODE = MAS.CUSTCODE 
        AND TOT.CNTRCODE = MAS.CNTRCODE
        AND TOT.CUSTCODE = '0100'
        AND MAS.SALTYPE <> 'RF'
        AND TOT.CALSTEP = '1' 
        AND :gADOP_ABOL_DAT BETWEEN MAS.ADOPDATE AND MAS.ABOLDATE
        AND TOT.CALMON = :gCALMON
        AND TOT.APRCNT+TOT.REJCNT+TOT.CANCNT+TOT.REJCANCNT <> 0
        GROUP BY TOT.CUSTCODE, TOT.CNTRCODE, MAS.CNTRNAME
        ORDER BY TOT.CUSTCODE, TOT.CNTRCODE, MAS.CNTRNAME                                                                                       
    ) TOT
WHERE 1=1
AND TOT.CUSTCODE = PRC.CUSTCODE 
AND TOT.CNTRCODE = PRC.CNTRCODE
;
